#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  4 10:45:15 2017

@author: brendontucker
"""

s = 7
t = 11
a = 5
b = 15
apples = [-2, 2, 1]
oranges =  [5, -6] #if these were bigger then we'd want to go for a dict
appleCounter = 0
orangeCounter = 0


for x in apples:
    if x + a in range(s,t):
        appleCounter += 1
print(appleCounter)
for x in oranges:
    if x + b in range(s,t):#because these repeated O(n) searches could add up
        orangeCounter += 1
print(orangeCounter)        
