#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr  2 18:50:23 2017

@author: brendontucker
"""

a = [[11, 2, 4], [4, 5, 6], [10, 8, -12]]

counter = 0
diagonalOne = 0
diagonalTwo = 0
while counter < len(a):
    diagonalOne += a[counter][counter]
    counter += 1
counter -= 1
counter2 = 0
while counter2 < len(a):
    diagonalTwo += a[counter2][counter]
    counter -= 1
    counter2 += 1
    
print (abs(diagonalOne - diagonalTwo))