#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  3 08:52:54 2017

@author: brendontucker
"""

theList = [1, 2, 3, 4, 5]

theList.sort()


print (sum(theList[:4]), sum(theList[1:]))