#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr  2 19:34:51 2017

@author: brendontucker
"""


arr = [-4, 3, -9, 0, 4, 1]
n = 6


positiveCount = 0
negativeCount = 0
zeroCount = 0
for x in arr:
    if x > 0:
        positiveCount += 1
    elif x < 0:
        negativeCount += 1
    elif x == 0:
        zeroCount += 1
        
print ("{0:.6f}".format(positiveCount/n)) 
print ("{0:.6f}".format(negativeCount/n))
print ("{0:.6f}".format(zeroCount/n))

