#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  3 07:34:31 2017

@author: brendontucker
"""

n = 6

spaceCount = n 
print(" " * spaceCount + "#")
counter = 1
diff = 0

        
while counter <= n:
    print(' ' * (spaceCount - counter) + '#' * counter)
    counter += 1