#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr  4 07:58:42 2017

@author: brendontucker
"""

arr = [[1, 1, 1, 0, 0, 0], 
       [0, 1, 0, 0, 0, 0], 
       [1, 1, 1, 0, 0, 0], 
       [0, 9, 2, -4, -4, 0], 
       [0, 0, 0, -2, 0, 0], 
       [0, 0, -1, -2, -4, 0]]
       
rightEnd = 3
midValue = 1
leftEnd = 0
topRow = 0
midRow = 1
bottomRow = 2
glassCounter = 0
maxVal = []



while bottomRow < 6:
    rightEnd = 3
    midValue = 1
    leftEnd = 0
    while rightEnd < 7: 
        glassCounter = sum(arr[topRow][leftEnd:rightEnd]) 
        glassCounter += arr[midRow][midValue]
        glassCounter += sum(arr[bottomRow][leftEnd:rightEnd])
        maxVal.append(glassCounter)
        glassCounter = 0
        rightEnd += 1
        midValue += 1
        leftEnd += 1
    topRow += 1
    midRow += 1
    bottomRow += 1
    