#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  3 15:39:45 2017

@author: brendontucker

simple problem, want to do it clean or pythonic though
"""

arr = [1, 4, 3, 2]
#arr = arr[::-1]

for x in arr[::-1]:
    print(x, end= " ")